In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [7]:
df = pd.read_csv(r'newPaperData.csv')
df

,Timestamp,Millitm,ZZ_CI\CIA001\AI_PV,ZZ_CI\CIA002\AI_PV,ZZ_CI\CIA003\AI_PV,ZZ_CI\CIC001\AI_PV,ZZ_CI\CIC002\AI_PV,ZZ_CI\CIC003\AI_PV,ZZ_CI\CIC004\AI_PV,ZZ_CI\CIC005\AI_PV,...,DZ_HMI\XX\Z1,DZ_HMI\XX\Z2,DZ_HMI\XX\Z3,DZ_HMI\XX\Z4,DZ_HMI\XX\Z5,DZ_HMI\XX\Z6,DZ_HMI\XX\Z701,DZ_HMI\XX\Z702,OTHER\CJD,Unnamed: 824
0,2024-06-06 00:00:01,955,1.5,1.5,1.5,3.075486,2.786284,0.352918,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
1,2024-06-06 00:00:02,814,1.5,1.5,1.5,3.075486,2.786284,0.352918,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
2,2024-06-06 00:00:05,928,1.5,1.5,1.5,3.090759,2.786965,0.353405,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
3,2024-06-06 00:00:09,72,1.5,1.5,1.5,3.099222,2.787062,0.352432,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
4,2024-06-06 00:00:12,152,1.5,1.5,1.5,3.102432,2.789591,0.352918,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27643,2024-06-06 23:59:48,50,1.5,1.5,1.5,3.111187,2.770720,0.352335,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27644,2024-06-06 23:59:51,123,1.5,1.5,1.5,3.111381,2.771498,0.352237,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27645,2024-06-06 23:59:54,246,1.5,1.5,1.5,3.107587,2.771595,0.352821,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27646,2024-06-06 23:59:57,380,1.5,1.5,1.5,3.105836,2.771498,0.353502,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27647,2024-06-07 00:00:01,269,1.5,1.5,1.5,3.104085,2.771693,0.353405,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN

In [9]:
df_deleteall0 = df.loc[:, ~(df == 0).all()]
# df.set_index('Timestamp', inplace=True) 设置索引
df_deleteall0

,Timestamp,Millitm,ZZ_CI\CIA001\AI_PV,ZZ_CI\CIA002\AI_PV,ZZ_CI\CIA003\AI_PV,ZZ_CI\CIC001\AI_PV,ZZ_CI\CIC002\AI_PV,ZZ_CI\CIC003\AI_PV,ZZ_CI\CIC004\AI_PV,ZZ_CI\CIC005\AI_PV,...,DZ_HMI\XX\Z1,DZ_HMI\XX\Z2,DZ_HMI\XX\Z3,DZ_HMI\XX\Z4,DZ_HMI\XX\Z5,DZ_HMI\XX\Z6,DZ_HMI\XX\Z701,DZ_HMI\XX\Z702,OTHER\CJD,Unnamed: 824
0,2024-06-06 00:00:01,955,1.5,1.5,1.5,3.075486,2.786284,0.352918,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
1,2024-06-06 00:00:02,814,1.5,1.5,1.5,3.075486,2.786284,0.352918,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
2,2024-06-06 00:00:05,928,1.5,1.5,1.5,3.090759,2.786965,0.353405,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
3,2024-06-06 00:00:09,72,1.5,1.5,1.5,3.099222,2.787062,0.352432,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
4,2024-06-06 00:00:12,152,1.5,1.5,1.5,3.102432,2.789591,0.352918,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27643,2024-06-06 23:59:48,50,1.5,1.5,1.5,3.111187,2.770720,0.352335,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27644,2024-06-06 23:59:51,123,1.5,1.5,1.5,3.111381,2.771498,0.352237,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27645,2024-06-06 23:59:54,246,1.5,1.5,1.5,3.107587,2.771595,0.352821,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27646,2024-06-06 23:59:57,380,1.5,1.5,1.5,3.105836,2.771498,0.353502,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN
27647,2024-06-07 00:00:01,269,1.5,1.5,1.5,3.104085,2.771693,0.353405,1.5,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN

In [10]:
corr_table=df_deleteall0.corr()
corr_table

ValueError: could not convert string to float: '2024-06-06 00:00:01'

In [ ]:
import seaborn as sns
plt.figure(figsize=(200, 160))  # 设置图形大小  
sns.heatmap(corr_table, annot=True, cmap='coolwarm', fmt=\".2f\")  # annot=True显示数值，cmap设置颜色映射，fmt设置数值格式  
plt.title('Correlation Heatmap')  # 设置标题  
plt.show()"